Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 7704818869678da2edf36c667c765d2aa0e5747b,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```