FileSystem dock: Fix open a terminal
The previous implementation of opening a terminal
in the FileSystem dock was causing errors due to the use
of a bash builtin command that does not work outside the shell.

This resulted in the following error messages:

	ERROR: Could not create child process: command
		at: execute (drivers/unix/os_unix.cpp:553)
	ERROR: Could not create child process: command
		at: execute (drivers/unix/os_unix.cpp:553)
	...

To resolve this issue,
+ the command is now executed inside a bash shell,
+ if the `terminal_emulator_flags` editor option is empty,
  the working directory for gnome-terminal and urxvt is now properly set.